CREATE SCHEMA IF NOT EXISTS `sample_spring_db` DEFAULT CHARACTER SET utf8 ;
USE `sample_spring_db`;

CREATE TABLE IF NOT EXISTS `todo` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(255) NOT NULL,
	`details` VARCHAR(255) NOT NULL,
	`finished` TINYINT(1) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE = InnoDB;
